### ISSUE TITLE
[REQUEST] Add more icons for material theme

### ISSUE THREAD

**Issue by AregevDev** [Almighty-Alpaca/JetBrains-Discord-Integration-Icons#1]
-toml
-bash

**Comment by AregevDev** [comment]
-cmake on the material theme is missing as well

**Comment by AregevDev** [comment]
All present now added Toml in the latest commit.

Icons I would like to add to the material theme (need to discuss with Alpaca)

- Archives (zip, rar, 7z, tar.gz, tar.xz)
- Vim (vim)
- Audio (mp3, ogg, wav)
- Cabal, Haskell's build system (cabal)
- Less (less)
- Nim (nim)
- Video (mp4, avi)
- Haxe (hx, hxml)

**Comment by Almighty-Alpaca** [comment]
Closing this in favor of the plugin rewrite
